#' @title Create a graph from network
#' 
#' @param network A named list of dataframes \code{nodes} and \code{edges} generated by \code{Create}.
#' @param directed Logical. Create a directed graph. Default is \code{TRUE}.
#' @param write_file Logical. Save graph to a file in the current working directory. Default is \code{FALSE}.
#' @param ... Additional parameters passed to function. Not used in this method.
#' 
#' @return An igraph object.
#' 
#' @aliases graph
#' @name vosonSML::graph
#' @export
graph <- function(network, directed = TRUE, write_file = FALSE, ...) {
  cat("Creating network graph...")
  if (write_file) { cat("\n") }
  
  # igraph warning converting a dataframe with an POSIXct column to an igraph object
  # https://github.com/igraph/rigraph/pull/250
  network$nodes %<>% dplyr::mutate_if(lubridate::is.POSIXt, as.character)
  network$edges %<>% dplyr::mutate_if(lubridate::is.POSIXt, as.character)
  
  if (!all(c("semantic", "twitter") %in% class(network))) {
    # create igraph object from dataframes
    g <- igraph::graph_from_data_frame(d = network$edges, directed = directed, vertices = network$nodes)
  }

  # searches the class list of network for matching method
  UseMethod("graph", network)
}

#' @noRd
#' @export
graph.default <- function(...) {
  stop("Unknown network type passed to graph.", call. = FALSE) 
}

#' @noRd
#' @method graph activity
#' @export
graph.activity <- function(network, directed = TRUE, write_file = FALSE, ...) {
  UseMethod("graph.activity", network)
}

#' @noRd
#' @export
graph.activity.default <- function(...) {
  stop("Unknown social media type passed to graph.", call. = FALSE)
}

#' @noRd
#' @export
graph.activity.twitter <- function(network, directed = TRUE, write_file = FALSE, ...) {
  g <- igraph::set_graph_attr(g, "vosonsml", c("activity", "twitter"))
  write_graph(g, "graphml", write_file, "TwitterActivity")
  cat("Done.\n")
  g
}

#' @noRd
#' @export
graph.activity.youtube <- function(network, directed = TRUE, write_file = FALSE, ...) {
  g <- igraph::set_graph_attr(g, "vosonsml", c("activity", "youtube"))
  write_graph(g, "graphml", write_file, "YoutubeActivity")
  cat("Done.\n")
  g
}

#' @noRd
#' @export
graph.activity.reddit <- function(network, directed = TRUE, write_file = FALSE, ...) {
  g <- igraph::set_graph_attr(g, "vosonsml", c("activity", "reddit"))
  write_graph(g, "graphml", write_file, "RedditActivity")
  cat("Done.\n")
  g
}

#' @noRd
#' @export
graph.activity.web <- function(network, directed = TRUE, write_file = FALSE, ...) {
  g <- igraph::set_graph_attr(g, "vosonsml", c("activity", "web"))
  write_graph(g, "graphml", write_file, "WebActivity")
  cat("Done.\n")
  g
}

#' @noRd
#' @method graph actor
#' @export
graph.actor <- function(network, directed = TRUE, write_file = FALSE, ...) {
  UseMethod("graph.actor", network)
}

#' @noRd
#' @export
graph.actor.default <- function(...) {
  stop("Unknown social media type passed to graph.", call. = FALSE)
}

#' @noRd
#' @export
graph.actor.twitter <- function(network, directed = TRUE, write_file = FALSE, ...) {
  g <- igraph::set_graph_attr(g, "vosonsml", c("actor", "twitter"))
  write_graph(g, "graphml", write_file, "TwitterActor")
  cat("Done.\n")
  g  
}

#' @noRd
#' @export
graph.actor.youtube <- function(network, directed = TRUE, write_file = FALSE, ...) {
  g <- igraph::set_graph_attr(g, "vosonsml", c("actor", "youtube"))
  write_graph(g, "graphml", write_file, "YoutubeActor")
  cat("Done.\n")
  g
}

#' @noRd
#' @export
graph.actor.reddit <- function(network, directed = TRUE, write_file = FALSE, ...) {
  g <- igraph::set_graph_attr(g, "vosonsml", c("actor", "reddit"))
  write_graph(g, "graphml", write_file, "RedditActor")
  cat("Done.\n")
  g  
}

#' @noRd
#' @export
graph.actor.web <- function(network, directed = TRUE, write_file = FALSE, ...) {
  g <- igraph::set_graph_attr(g, "vosonsml", c("actor", "web"))
  write_graph(g, "graphml", write_file, "WebActor")
  cat("Done.\n")
  g
}

#' @noRd
#' @method graph semantic
#' @export
graph.semantic <- function(network, directed = FALSE, write_file = FALSE, ...) {
  UseMethod("graph.semantic", network)
}

#' @noRd
#' @export
graph.semantic.default <- function(...) {
  stop("Unknown social media type passed to graph.", call. = FALSE)
}

#' @noRd
#' @export
graph.semantic.twitter <- function(network, directed = FALSE, write_file = FALSE, ...) {
  g <- igraph::graph_from_data_frame(d = network$edges, directed = directed, vertices = network$nodes)
  g <- igraph::set_graph_attr(g, "vosonsml", c("semantic", "twitter"))
  write_graph(g, "graphml", write_file, "TwitterSemantic")
  cat("Done.\n")
  g
}

#' @noRd
#' @method graph twomode
#' @export
graph.twomode <- function(network, directed = TRUE, write_file = FALSE, ...) {
  UseMethod("graph.twomode", network)
}

#' @noRd
#' @export
graph.twomode.default <- function(...) {
  stop("Unknown social media type passed to graph.", call. = FALSE)
}

#' @noRd
#' @export
graph.twomode.twitter <- function(network, directed = TRUE, write_file = FALSE, ...) {
  g <- igraph::set_graph_attr(g, "vosonsml", c("twomode", "twitter"))
  write_graph(g, "graphml", write_file, "Twitter2mode")
  cat("Done.\n")
  g  
}

# set output file name
# if wtof is logical use def as file name
# if character use wtof as file name
write_graph <- function(g, type, wtof, def) {
  if (is.logical(wtof) && wtof) { 
    write_output_file(g, "graphml", def) 
  } else if (is.character(wtof)) {
    write_output_file(g, "graphml", wtof)
  }  
}
